### ISSUE TITLE
fix(ftp): develop broken — FTP FileEntry construction missing writable field added by #1324

### ISSUE THREAD

**Issue by armaxri** [armaxri/termiHub#1488]
## Problem — develop does not compile
Two PRs merged with no textual conflict but a semantic one:
- **#1478 (#1324, SFTP read-only detection)** added a new `writable` field to `FileEntry`.
- **#1475 (#1456, FTP file browser)** constructs `FileEntry` in `core/src/backends/ftp/listing_parser.rs` (and `file_browser.rs`) without that field.

CI on every PR now fails Rust build/clippy/tests on all platforms:
```
error[E0063]: missing field `writable` in initializer of `files::FileEntry`
  --> core/src/backends/ftp/listing_parser.rs:97:10
```

This is a develop-wide breakage — unrelated frontend PRs (e.g. #1487) fail because they inherit it via their develop merge.

## Scope
- [ ] Add the `writable` field to every `FileEntry` initializer in the FTP backend (`core/src/backends/ftp/listing_parser.rs`, `core/src/backends/ftp/file_browser.rs`, and any other FTP construction sites) so the workspace compiles.
- [ ] Use the semantically-correct value: FTP listings generally don't carry authoritative writability, so `writable: None` (unknown) is the conservative default — UNLESS an MLSD `perm` fact is already parsed and cheaply available, in which case derive it consistently with how SFTP does (`writable_from_permissions`), else `None`.
- [ ] Confirm `cargo build --workspace --all-features` and `cargo clippy --workspace --all-targets --all-features -- -D warnings` are green.
- [ ] Add/extend a test if one cheaply pins the FTP `FileEntry.writable` value.

## Done when
`develop` compiles again: `cargo clippy --workspace --all-targets --all-features -- -D warnings` passes, FTP `FileEntry` construction sets `writable`, and CI Rust build/tests pass.

**Comment by armaxri** [comment]
Already fixed on develop by PR #1485 (dev0/feature/1482-ssh-ftp-writable, 'derive FileEntry.writable in SSH and FTP browsers'), which is current develop HEAD. cargo build --workspace --all-features is green. Closing as resolved — no separate fix needed.
